commerce_payment.commerce_payment_gateway.plugin.paytabs_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_email:
      type: string
      label: 'Profile id'
    secret_key:
      type: string
      label: 'Server key'
    merchant_region:
      type: string
      label: 'region'
    pay_page_mode:
      type: string
      label: 'Pay Page Mode'
    complete_order_status:
      type: string
      label: 'complete order status'
